<a href="https://colab.research.google.com/github/Charlene393/MachineLearning-basics/blob/main/CrossValidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Cross validationn helps you evaluate the performance of a model

option 1) Use all available data for training and test on same dataset. Use the same training dataset to test. There is a problem in this type of dataset the training and the test sets are the same so not much learning is done
option 2) Split available dataset into training and test sets. There is a problem in this the training set might be completely different from what the test set is there the model might fail to learn
Option 3) K fold cross validation. We divide our dataset into folds, then run multiple iteration. For the first Iteration you use firt fold and get the score. THe second iteration you use the second fold and record the score you get. You repeat the process till the 5th iteration. Then get the average score
'''

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [15]:
#WE WILL USE DIFFERENT MODELS AND TEST THEM USING K FOLD. For spliting method the training dataset keeps on changing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [16]:
#Logistic Regression
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [17]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9925925925925926

In [19]:
rf = RandomForestClassifier(n_estimators= 40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9722222222222222

In [26]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 9)
kf

KFold(n_splits=9, random_state=None, shuffle=False)

In [27]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index, test_index)

[1 2 3 4 5 6 7 8] [0]
[0 2 3 4 5 6 7 8] [1]
[0 1 3 4 5 6 7 8] [2]
[0 1 2 4 5 6 7 8] [3]
[0 1 2 3 5 6 7 8] [4]
[0 1 2 3 4 6 7 8] [5]
[0 1 2 3 4 5 7 8] [6]
[0 1 2 3 4 5 6 8] [7]
[0 1 2 3 4 5 6 7] [8]


In [30]:
def get_score(model, x_train, x_test, y_train, y_test):
  model.fit(x_train, y_train)
  return model.score(x_test, y_test)

In [35]:
#This better it divides the folds in a uniform way
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [44]:
scores_1 =[]
scores_svm = []
scores_rf =[]

for train_index, test_index in kf.split(digits.data):
  x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
  scores_1.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
  scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators= 40), x_train, x_test, y_train, y_test))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [46]:
scores_1

[0.905,
 0.975,
 0.895,
 0.905,
 0.965,
 0.96,
 0.9296482412060302,
 0.8994974874371859,
 0.9296482412060302]

In [45]:
scores_svm

[0.95,
 0.98,
 0.96,
 0.985,
 0.985,
 0.99,
 0.9949748743718593,
 0.9698492462311558,
 0.9396984924623115]

In [47]:
scores_rf

[0.905,
 0.96,
 0.93,
 0.925,
 0.96,
 0.96,
 0.9698492462311558,
 0.9698492462311558,
 0.914572864321608]

In [48]:
from sklearn.model_selection import cross_val_score

In [51]:
cross_val_score(LogisticRegression(),digits.data, digits.target)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [57]:
cross_val_score(SVC(C =100),digits.data, digits.target)

array([0.98055556, 0.95833333, 0.98328691, 0.98885794, 0.95821727])

In [56]:
cross_val_score(RandomForestClassifier(n_estimators=56),digits.data, digits.target)

array([0.91666667, 0.89444444, 0.9637883 , 0.95543175, 0.91922006])