<a href="https://colab.research.google.com/github/Charlene393/MachineLearning-basics/blob/main/HyperParameterTuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#The process of choosing the optimal attributes is called hypertuning

'\n'

In [2]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [4]:
import pandas as pd
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[23:52]

sepal length (cm)  sepal width (cm)  ...  petal width (cm)      flower
23                5.1               3.3  ...               0.5      setosa
24                4.8               3.4  ...               0.2      setosa
25                5.0               3.0  ...               0.2      setosa
26                5.0               3.4  ...               0.4      setosa
27                5.2               3.5  ...               0.2      setosa
28                5.2               3.4  ...               0.2      setosa
29                4.7               3.2  ...               0.2      setosa
30                4.8               3.1  ...               0.2      setosa
31                5.4               3.4  ...               0.4      setosa
32                5.2               4.1  ...               0.1      setosa
33                5.5               4.2  ...               0.2      setosa
34                4.9               3.1  ...               0.2      setosa
35                5.0               3.2  ...               0.2      setosa
36                5.5               3.5  ...               0.2      setosa
37                4.9               3.6  ...               0.1      setosa
38                4.4               3.0  ...               0.2      setosa
39                5.1               3.4  ...               0.2      setosa
40                5.0               3.5  ...               0.3      setosa
41                4.5               2.3  ...               0.3      setosa
42                4.4               3.2  ...               0.2      setosa
43                5.0               3.5  ...               0.6      setosa
44                5.1               3.8  ...               0.4      setosa
45                4.8               3.0  ...               0.3      setosa
46                5.1               3.8  ...               0.2      setosa
47                4.6               3.2  ...               0.2      setosa
48                5.3               3.7  ...               0.2      setosa
49                5.0               3.3  ...               0.2      setosa
50                7.0               3.2  ...               1.4  versicolor
51                6.4               3.2  ...               1.5  versicolor

[29 rows x 5 columns]

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.3)

In [6]:
model = svm.SVC(kernel = 'rbf', C = 20, gamma = 'auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.9777777777777777

In [8]:
from sklearn.model_selection import cross_val_score

In [9]:
#We use k-fold validation because the data samples keeps on changing. We split the data in fold
cross_val_score(svm.SVC(kernel = 'linear', C = 10, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [10]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 10, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [11]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 20, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [13]:
#You can run the above 3 codes using a for loop. This procedure also has errors because if C has 4 , you have to repeat the iteration 4 times, which is a lot of iterations. Sklearn has gridsearchCv that solves the problem.
import numpy as np
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores ={}
for kval in kernels:
  for cval in C:
    cv_scores = cross_val_score(svm.SVC(kernel = kval, C = cval, gamma = 'auto'), iris.data, iris.target, cv = 5)
    avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores

{'rbf_1': np.float64(0.9800000000000001),
 'rbf_10': np.float64(0.9800000000000001),
 'rbf_20': np.float64(0.9666666666666668),
 'linear_1': np.float64(0.9800000000000001),
 'linear_10': np.float64(0.9733333333333334),
 'linear_20': np.float64(0.9666666666666666)}

In [16]:
#GridSearcgCv
from sklearn.model_selection import GridSearchCV

GSV = GridSearchCV(svm.SVC(gamma = 'auto'),{
    'C':[1,10,20],
    'kernel':['rbf', 'linear']
}, cv = 5, return_train_score = False)

GSV.fit(iris.data, iris.target)
GSV.cv_results_

{'mean_fit_time': array([0.00130877, 0.0009809 , 0.00100799, 0.00090466, 0.00097852,
        0.00089107]),
 'std_fit_time': array([3.66764519e-04, 1.01184845e-04, 1.79606272e-05, 3.11596209e-05,
        2.66617219e-05, 1.55031486e-05]),
 'mean_score_time': array([0.00085306, 0.0007154 , 0.00073047, 0.00067735, 0.00070305,
        0.00068507]),
 'std_score_time': array([1.21762868e-04, 1.97635053e-05, 1.21555135e-05, 8.31530725e-06,
        9.56459746e-06, 1.39033810e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
 

In [17]:
df = pd.DataFrame(GSV.cv_results_)
df

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.001309      0.000367  ...        0.016330                1
1       0.000981      0.000101  ...        0.016330                1
2       0.001008      0.000018  ...        0.016330                1
3       0.000905      0.000031  ...        0.038873                4
4       0.000979      0.000027  ...        0.036515                5
5       0.000891      0.000016  ...        0.042164                6

[6 rows x 15 columns]

In [18]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [19]:
GSV.best_score_

np.float64(0.9800000000000001)

In [20]:
GSV.best_params_

{'C': 1, 'kernel': 'rbf'}

In [21]:
#Randomized search cv can be used as an alternative due to the high computational cost of the gridsearchcv. This work well when you have low computational power

from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma = 'auto'),{
    'C':[1,10,20],
    'kernel':['rbf', 'linear']
},
  cv = 5,
  return_train_score = False,
  n_iter = 2)

rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]


param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1       10       linear         0.973333

In [22]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [24]:
model_params ={
    'svm':{
        'model':svm.SVC(gamma = 'auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf', 'linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(solver = 'liblinear', multi_class = 'auto'),
        'params':{
            'C':[1,5,10]
        }
    }
}


In [25]:
scores = []
#cv is cross validation
for model_name, mp in model_params.items():
  GSV = GridSearchCV(mp['model'], mp['params'], cv = 5, return_train_score = False)
  GSV.fit(iris.data, iris.target)
  scores.append({
      'model':model_name,
      'best_score':GSV.best_score_,
      'best_params':GSV.best_params_
  })

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and wi

In [26]:
df = pd.DataFrame(scores, columns = ['model', 'best_score', 'best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333        {'n_estimators': 1}
2  logistic_regression    0.966667                   {'C': 5}